### ISSUE TITLE
Trait std::error::Error not implemented for amiquip::error

### ISSUE THREAD

**Issue by mkeedlinger** [jgallagher/amiquip#10]
[Error is a trait](https://doc.rust-lang.org/std/error/trait.Error.html) that "[represents] the basic expectations for error values".

It should be easy to implement, the problem is that your implementation of `failure::Fail` conflicts because of the `cause` function. I was hoping there might be an updated version of `failure` that had fixed the issue and you could simply upgrade, but sadly the most recent version<sup>1</sup> [still has the collision](https://docs.rs/failure/0.1.5/failure/trait.Fail.html#provided-methods).

Not sure the easiest way forward. For now I plan to fork and create a nasty fix that probably involves making another kind of Error struct that wraps yours and correctly implements the std Error trait.

1: Version 0.1.5 at time of writing this

**Comment by mkeedlinger** [comment]
For those who are interested, here's my quick fix: https://github.com/mkeedlinger/amiquip/commit/d64a0a03cb977907c8b8a1e39afd19b2f05feb5c

**Comment by jgallagher** [comment]
Hm, that's not great. I've been using [snafu](https://crates.io/crates/snafu) recently and really liked it; maybe I should switch to that for amiquip?

**Comment by mkeedlinger** [comment]
It looks like they implement the `Error` trait, so sounds good to me!

**Comment by jgallagher** [comment]
[0.3.0](https://crates.io/crates/amiquip) is live; `Error` now impls `std::error::Error`.

**Comment by mkeedlinger** [comment]
Very cool!
