### ISSUE TITLE
Crate dont compile

### ISSUE THREAD

**Issue by fgt-moma** [jgallagher/amiquip#12]
Just adding amiquip in a new project, I have this error with 'cargo build' :

> error: expected `=`
>   --> <...>/.cargo/registry/src/github.com-1ecc6299db9ec823/amiquip-0.3.0/src/errors.rs:250:10
>    |
>250 |     #[doc(hidden)]
>    |          ^^^^^^^^

**Comment by jgallagher** [comment]
Hm, that's odd. What version of rust and cargo are you using?

**Comment by fgt-moma** [comment]
May be it's a change in some dependency ?

cargo 1.36.0 (c4fcfb725 2019-05-15)
rustup 1.18.3 (435397f48 2019-05-22)
rustc 1.36.0 (a53f9df32 2019-07-03)

**Comment by jgallagher** [comment]
Can you put a project that has this error somewhere so I can reproduce it?

**Comment by fgt-moma** [comment]
In fact, I just create a new project.
Add 'amiquip = "0.3.0"' in 'Cargo.toml' 
Try to compile ... and it's result with the above error.
(Tryed on a coworker PC ... same result)

**Comment by fgt-moma** [comment]
Just commented out line /src/errors.rs:250 and all work fine now ...

**Comment by jgallagher** [comment]
It was indeed a breaking change in a dependency! Sorry for the long delay on this. I opened [an issue](https://github.com/shepmaster/snafu/issues/139) there asking about the change, and just published 0.3.1 which removes the `#[doc(hidden)]` for now as you suggested. I'd like to leave this issue open for now, and plan to publish a 0.3.2 restoring `#[doc(hidden)]` once I can.

**Comment by fgt-moma** [comment]
Thanks a lot and sorry for the long delay (holiday).
