### ISSUE TITLE
URI params: cacertfile

### ISSUE THREAD

**Issue by fewzee** [jgallagher/amiquip#13]
Hi John, I understand that the cacertfile is not supported at the current iteration. Is there any work around for it? As a side-note, I would be more than happy to contribute to the package.

**Comment by jgallagher** [comment]
Hi! If you need more fine-grained control over the SSL setup (I do this in a project that uses amiquip), you can use the [`Connection::open_tls_stream`](https://docs.rs/amiquip/0.3.1/amiquip/struct.Connection.html#method.open_tls_stream) method that allows you to pass in your own `TlsConnector`. If you want to take a crack at adding support for cacertfile, I'd be happy to take a look.

**Comment by fewzee** [comment]
Thank you for your response. TlsConnector doesn't seem to provide any way to certify connections. How do you get more fine-grained control for your project?

**Comment by jgallagher** [comment]
You can configure a `TlsConnector` using [`native_tls::TlsConnectorBuilder`](https://docs.rs/native-tls/0.2.3/native_tls/struct.TlsConnectorBuilder.html). I don't have code in front of me, so this probably isn't quite right, but something like:

```rust
let tls_connector = native_tls::TlsConnector::builder()
    .identity(...)
    .add_root_certificate(...)
    .build()
    .expect("failed to build TlsConnector");
```

**Comment by fewzee** [comment]
Thank you John. Here's what I've got so far:
```
use amiquip::{
    Auth,
    Connection,
    ConnectionOptions,
    ConnectionTuning,
    Exchange,
    Publish,
    Result
};
use native_tls::{Certificate, TlsConnector};
use std::fs;
use mio::net::TcpStream;
use std::time::Duration;

struct Rabbit {
    host: String,
    port: usize,
    username: String,
    password: String,
    vhost: String,
    secure: bool,
    cafile: String,
}

impl Rabbit {
    fn get_string(&self) -> String {
        format!("{protocol}://{username}:{password}@{host}:{port}/{vhost}",
            protocol=if self.secure {"amqps"} else {"amqp"},
            username=self.username,
            password=self.password,                                                                                                                                                   
            host=self.host,                                                                                                                                                           
            port=self.port,                                                                                                                                                           
            vhost=self.vhost,                                                                                                                                                         
        ) 
    }

    fn get_stream(&self) -> TcpStream {
        let address = format!("{host}:{port}",
            host=self.host,
            port=self.port,
        );
        TcpStream::connect(&address[..].parse().unwrap()).unwrap()
    }

    fn get_cert(&self) -> Certificate {
        let cert_byte_vec = fs::read(self.cafile)
            .expect("failed to load cert");
        Certificate::from_pem(&cert_byte_vec)
            .expect("failed to parse cert")
    }
}
```
and in the main:
```
    let connector = TlsConnector::builder()
        .add_root_certificate(rabbit.get_cert())
        .build();
    let connection = Connection::open_tls_stream(
        connector,
        &(rabbit.host)[..],
        rabbit.get_stream(),
        ConnectionOptions::default()
            .auth(Auth::Plain {
                username: rabbit.username,
                password: rabbit.password,
            })
            .heartbeat(30)
            .channel_max(1024)
            .connection_timeout(Some(Duration::from_millis(10_000))),
        ConnectionTuning::default(),
    );
```
and, I'm getting this:
```
error[E0277]: the trait bound `amiquip::stream::native_tls::TlsConnector: std::convert::From<std::result::Result<native_tls::TlsConnector, native_tls::Error>>` is not satisfied
  --> src/main.rs:71:22
   |
71 |     let connection = Connection::open_tls_stream(
   |                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^ the trait `std::convert::From<std::result::Result<native_tls::TlsConnector, native_tls::Error>>` is not implemented for `amiquip::stream::native_tls::TlsConnector`
   |
   = help: the following implementations were found:
             <amiquip::stream::native_tls::TlsConnector as std::convert::From<native_tls::TlsConnector>>
   = note: required because of the requirements on the impl of `std::convert::Into<amiquip::stream::native_tls::TlsConnector>` for `std::result::Result<native_tls::TlsConnector, native_tls::Error>`
   = note: required by `amiquip::connection::Connection::open_tls_stream`
```

What am I missing?

**Comment by jgallagher** [comment]
This part:

```
the trait `std::convert::From<std::result::Result<native_tls::TlsConnector, native_tls::Error>>` is not implemented for `amiquip::stream::native_tls::TlsConnector
```

is saying you can't convert a `Result<native_tls::TlsConnector, native_tls::Error>` into an `amiquip::TlsConnector`. Below that, it tells you what conversion was found:

```
   = help: the following implementations were found:
             <amiquip::stream::native_tls::TlsConnector as std::convert::From<native_tls::TlsConnector>>
```

So: you can' convert a `Result<native_tls::TlsConnector, ...>` into an amiquip `TlsConnector`, but you can convert a `native_tls::TlsConnector` directly. That means you need to unwrap (or otherwise handle) the possible error coming from `.build()`, and assuming that was successful, pass the `native_tls::TlsConnector` in instead of the `Result`. Does that make sense?

**Comment by fewzee** [comment]
Yes, it makes sense. Thank you for your help, John, and for your patience with my questions, that are not necessarily amiquip questions, but are due to my lack of experience with the language.

It's not compiling and running with no error, although I'm not seeing the queue created on rabbit. I'll look into this more and will update you on the progress.

**Comment by Tamircohen28** [comment]
hey,
i am using amiquip 0.4 and I receive the following error

> error[E0277]: the trait bound `mio::net::TcpStream: IoStream` is not satisfied
   --> src\main.rs:68:26
    |
68  |     let mut connection = Connection::open_tls_stream(connector, &rabbit.host, rabbit.get_stream(), ConnectionOptions::default(), Connecti...
    |                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^ the trait `IoStream` is not implemented for `mio::net::TcpStream`
    | 
   ::: C:\Users\Tamir Cohen\.cargo\registry\src\github.com-1ecc6299db9ec823\amiquip-0.4.0\src\connection.rs:262:66
    |
262 |     pub fn open_tls_stream<Auth: Sasl, C: Into<TlsConnector>, S: IoStream>(
    |                                                                  -------- required by this bound in `Connection::open_tls_stream`

I couldn't find any solution and this is the only place online I saw about rabbit client using TLS with rust.

**Comment by jgallagher** [comment]
Hmm, that's odd, `IoStream` is definitely implemented for `mio::net::TcpStream` (https://docs.rs/amiquip/0.4.0/amiquip/trait.IoStream.html#impl-IoStream-for-TcpStream).

Is this maybe a version mismatch? `amiquip` uses `mio 0.6` (see #20 for context on that) - are you using a different version of `mio`?

**Comment by Tamircohen28** [comment]
yes! thanks!

**Comment by Tamircohen28** [comment]
I'm trying to use TlsConnector as said
```
    let connector = TlsConnector::builder()
        .add_root_certificate(rabbit.get_cert())
        .build()
        .unwrap();
```
where `rabbit.get_cert()` read the client_certificate.pem file into Certificate instance.
I don't get any response from the rabbit server.
when using OpenSSL tool as following:
`openssl s_client -connect localhost:5671 -cert client_certificate.pem -key client_key.pem -CAfile ca_certificate.pem`
i get response.
i noticed the SSL uses also key and CA files, how should i pass them to the TlsConnector?

**Comment by jgallagher** [comment]
SSL questions are mostly outside the realm of `amiquip`, so not sure I'll be able to help too much more. But I believe for client certs you have to pass that to the builder via [identity()](https://docs.rs/native-tls/0.2.4/native_tls/struct.TlsConnectorBuilder.html#method.identity).

**Comment by nick9822** [comment]
@jgallagher I think we must add one example of `open_tls_stream` in the readme doc. I think most of the users who need TLS, mostly will need control over `TlsConnector`. I can add one example of the same.
