### ISSUE TITLE
support quorem queues

### ISSUE THREAD

**Issue by volfco** [jgallagher/amiquip#17]
running rabbitmq 3.8.1 with a quorem queue fails with the default configuration.

My code: 

```    let mut rmq_conn = rmq_conn;
    let channel = rmq_conn.open_channel(None)?;
    let mut options = QueueDeclareOptions::default();
    options.durable = true;
    let queue = channel.queue_declare("axfrd_tasks", options)?;
```

Error:
`Err(ServerClosedChannel { channel_id: 1, code: 406, message: "PRECONDITION_FAILED - inequivalent arg \'x-queue-type\' for queue \'axfrd_tasks\' in vhost \'/\': received none but current is the value \'quorum\' of type \'longstr\'" })`

**Comment by volfco** [comment]
Fix is adding 
`options.arguments.insert("x-queue-type".to_string(), AmqpValue::LongString("quorum".to_string()));` 
to the options. 

Not sure how (if) this should be addressed.

**Comment by jgallagher** [comment]
I don't think there's anything to do here, really. The RabbitMQ [docs for declaring quorum queues](https://www.rabbitmq.com/quorum-queues.html#declaring) are pretty explicit.

It wouldn't hurt to add some examples to the docs, though. I'll see about adding some examples to any of the types that take a `FieldTable` of arguments.
