### ISSUE TITLE
durable=false  connect failed  in docker 

### ISSUE THREAD

**Issue by somewheve** [jgallagher/amiquip#22]
First of all, I don't know the error happened  

I try to use amiquip to build a queue which durable=false in docker,  
I have set the durable=true 
```
  let exchange = channel.exchange_declare(
            ExchangeType::Topic,
            &client.exchange,
            ExchangeDeclareOptions {
                durable: false,
                auto_delete: false,
                internal: false,
                arguments: Default::default(),
            },
        )?;
```
this is the error message.  
```
qarealtimep_rs_ctp         | INFO： 从MQ在中订阅失败 原因ServerClosedChannel { channel_id: 1, code: 406, message: "PRECONDITION_FAILED - inequivalent arg \'durable\' for exchange \'CTPPRO\' in vhost \'/\': received \'true\' but current is \'false\'" }
```
but it works well in the physical host.  
for some reason, I can't provide example.  
I'm not very familiar with this, Hope for your help. 

> durable=true works well  in docker

**Comment by jgallagher** [comment]
I think that error message is saying that you tried to declare the exchange as durable=true (although your code snippet has it as false? just a typo maybe?), but the server has that exchange configured as durable=false. If the exchange already exists on the server, the client's config has to match.

**Comment by somewheve** [comment]
but it works on the physical machine..

**Comment by somewheve** [comment]
I have found this issue caused by the local git didn't update,   the git primary key does not work,

**Comment by somewheve** [comment]
Thanks for your reply
