### ISSUE TITLE
Consider inverting `native-tls` flag

### ISSUE THREAD

**Issue by grahamc** [jgallagher/amiquip#3]
Hello John!

This looks great!

I myself have maintained a fork of the rust-amqp library for a few years now, and look forward to experimenting and exercising this one. In particular, I like the break-down in to Exchange-specific implementations, etc. I also appreciate that it isn't heavily based on Futures.
 
One thing I would controversially like you to consider is inverting the language of `native-tls`. Right now, it says:

> By default, amiquip cannot use a TLS connection. To enable TLS connections, use the `native-tls` feature

However I see this is a a real loss for users and security. Many developers won't see this, won't consider the implications of TLS, and will leave their RabbitMQ instances exposed and insecure.  Especially given the sensitive information often exchanged over AMQP, and since we're making such great improvements with [70-90% of Firefox web requests being served over TLS](https://letsencrypt.org/stats/#percent-pageloads).

Concretely, my request is to invert this and say something like:

> By default, amiquip will only connect over TLS. To enable unsafe connections, use the `insecure-connections`:
> ```toml
> [dependencies]
> amiquip = { version = "0.1", features = ["insecure-connections"] }
> ```

This is a tough default to set, but since amiquip is a new library -- it is at the easiest point to move away from a default-insecure configuration.

Anyway, I hope you'll consider this a bit.

I look forward to trying it out, with or without this change :) 

Best,
Graham

**Comment by grahamc** [comment]
PS: Thank you a _**lot**_ for investing time and effort in to making a great amqp lib!

**Comment by jgallagher** [comment]
Thanks for the kind words!

I like this suggestion. My main concern about implementing it is local development: Installing RabbitMQ (e.g., in a VM) for development is very easy, but I believe setting up a localhost TLS-enabled instance is quite a bit trickier. If folks enable insecure connections for development, I feel like this change would lose most of its oompf, as then they have to remember to turn it back off again before moving into production. Even the examples in this repo try to connect to `amqp://guest:guest@localhost`; presumably they would either have to change to amqps (and require users to have a TLS-enabled Rabbit instance running on localhost), or they would fail to run unless the insecure-connections feature was enabled, which again encourages users to put that feature in just to get started.

One alternative would be to do something like [native-tls itself does](https://docs.rs/native-tls/0.2.2/native_tls/struct.TlsConnectorBuilder.html#method.danger_accept_invalid_hostnames): 

1. Remove the `native-tls` feature and make it a hard dependency
2. Make `Connection::open` only support `amqps://...` URLs.
3. Add `Connection::danger_open` that allows `amqp://...`.
4. Rename `Connection::open_stream` to `Connection::danger_open_stream`.

I don't know that "danger" is the right prefix; maybe "unencrypted" or "insecure" would be better. But whatever the name is, we could keep the examples, and it would still be easy to develop with a localhost Rabbit, but there would be an obvious reminder in the source that something insecure was going on.

What do you think?

**Comment by jgallagher** [comment]
Hm, had another thought. It's not unheard of for `native-tls` to have difficulties building (has to find and link against OpenSSL, which is an extra step that can go wrong above pure Rust). So in the context of the suggestion in the previous comment, I wonder if there should still be an `insecure-connections` feature that would only expose the `Connection::insecure_*` methods, so if someone does run into openssl problems they can still at least try things out.

**Comment by jgallagher** [comment]
Decided to go with leaving unencrypted connections available as `Connection::insecure_open*` and leaving `native-tls` as a feature that can be disabled (but is on by default). Hopefully that hits a reasonable middle ground between encouraging secure use and usability for getting started and localhost development.
