### ISSUE TITLE
Specify a name for a new exchange

### ISSUE THREAD

**Issue by tappoz** [jgallagher/amiquip#31]
Is there a way to create a new exchange providing a name for it?

Looking here https://github.com/jgallagher/amiquip/blob/master/src/exchange.rs#L149 seems like the `name` is not exposed. We can retrieve this `name` (see here https://github.com/jgallagher/amiquip/blob/master/src/exchange.rs#L154), but we cannot set it to something we inject.

Is there a work around to this? So we can set our own preference for the Exchange name.

**Comment by jgallagher** [comment]
The method you linked to is specifically for getting a handle to the direct exchange (which has no name); I think you want to use one of

* https://docs.rs/amiquip/0.4.0/amiquip/struct.Channel.html#method.exchange_declare
* https://docs.rs/amiquip/0.4.0/amiquip/struct.Channel.html#method.exchange_declare_nowait
* https://docs.rs/amiquip/0.4.0/amiquip/struct.Channel.html#method.exchange_declare_passive

to declare an exchange; all three of those methods take an argument for the name.
