### ISSUE TITLE
Can no longer compile without TLS

### ISSUE THREAD

**Issue by SpootDev** [jgallagher/amiquip#36]
Rust 1.57, 2022

   Compiling amiquip v0.4.1
error[E0425]: cannot find value `TlsFeatureNotEnabled` in this scope
   --> /root/.cargo/registry/src/github.com-1ecc6299db9ec823/amiquip-0.4.1/src/connection.rs:469:9
    |
469 |         TlsFeatureNotEnabled.fail()
    |         ^^^^^^^^^^^^^^^^^^^^
    |
   ::: /root/.cargo/registry/src/github.com-1ecc6299db9ec823/amiquip-0.4.1/src/errors.rs:10:10
    |
10  | #[derive(Snafu, Debug)]
    |          ----- similarly named unit struct `TlsFeatureNotEnabledSnafu` defined here
    |
help: a unit struct with a similar name exists
    |
469 |         TlsFeatureNotEnabledSnafu.fail()
    |         ~~~~~~~~~~~~~~~~~~~~~~~~~
help: consider importing this unit variant
    |
416 |     use crate::Error::TlsFeatureNotEnabled;
    |

**Comment by jgallagher** [comment]
Yikes! That's one I missed in #34. Will fix and release 0.4.2 later today. Thanks for the report.

**Comment by jgallagher** [comment]
0.4.2 is now available, and #37 added a `--no-default-features` test to CI, which will hopefully prevent this from reoccurring in the future. Thanks again.

**Comment by SpootDev** [comment]
Thanks!
