### ISSUE TITLE
request/reply question

### ISSUE THREAD

**Issue by brandonros** [jgallagher/amiquip#38]
https://github.com/jgallagher/amiquip/blob/main/examples/rpc_client.rs#L50

Will the consumer sit and receive lots of messages and wait until *just* the correct correlation-id response is received? Is there anyway to subscribe only to the response we want and no other messages?

**Comment by jgallagher** [comment]
Apologies for the absurdly long delay on responding, but you are correct that that example will silently discard any incoming messages that do not match the correlation-id. I don't believe AMQP provides a way for clients to filter messages coming from a queue, although I think you can set up filters on _exchanges_ that then route to different queues.

**Comment by brandonros** [comment]
So the common pattern would be:

1. construct your own "ephemeral" queue for your one off response as a client
2. put the request in a different queue just for requests

how would you instruct that request to reply to that "reply" queue? trying to go for a request/reply example that is efficient and won't receive replies about requests it didn't issue?

**Comment by jgallagher** [comment]
Oh, the RPC example actually does that! The short answer is that the request needs to include the queue name somehow, and the server has to use that queue name when replying. In the RPC example, the client [creates an exclusive queue](https://github.com/jgallagher/amiquip/blob/main/examples/rpc_client.rs#L22) and then [includes that queue's name in its request as the reply-to property](https://github.com/jgallagher/amiquip/blob/main/examples/rpc_client.rs#L44). The server [rejects messages without a reply-to](https://github.com/jgallagher/amiquip/blob/main/examples/rpc_server.rs#L47) and [uses the reply-to contents as the name of the queue when sending the response](https://github.com/jgallagher/amiquip/blob/main/examples/rpc_server.rs#L60).
