### ISSUE TITLE
Cell<bool>` cannot be shared between threads safely within `Consumer<'_>`

### ISSUE THREAD

**Issue by alchymia-sys** [jgallagher/amiquip#49]
Is there a possible way to overried Cell<bool> in Consumer?

`Cell<bool>` cannot be shared between threads safely
within `Consumer<'_>`, the trait `std::marker::Sync` is not implemented for `Cell<bool>`, which is required by `{closure@src/bin/client.rs:83:13: 83:51}: MessageHandler<LocalAdapter, _>`
if you want to do aliasing and mutation between multiple threads, use `std::sync::RwLock` or `std::sync::atomic::AtomicBool` instead
required for `Arc<Consumer<'_>>` to implement `Send`

**Comment by jgallagher** [comment]
That is not possible, no. This is discussed in the [Thread Support](https://docs.rs/amiquip/latest/amiquip/#thread-support) section of the documentation; you need to declare the consumer in the same thread where you want to use it.
